### ISSUE TITLE
Which version is the playground using?

### ISSUE THREAD

**Issue by anubhakushwaha** [coreos/etcdlabs#284]
Which version of etcd(2/3) is used in the playground? Thanks

**Comment by gyuho** [comment]
We use etcd 3 with embedded etcd. Here's dependency spec https://github.com/coreos/etcdlabs/blob/master/Gopkg.toml.

**Comment by anubhakushwaha** [comment]
@gyuho Perfect, thank you.
You can close the issue as well.
